"use client";
import { useEffect,useState } from "react";
import { AppHeader } from "@/components/app-header";
import { FactCard } from "@/components/fact-card";
import { ManualFallback } from "@/components/manual-fallback";
import type { AnalysisRecord,ContentArtifact } from "@/lib/domain";
import { roomIdForSource } from "@/lib/rooms/id";

const stageLabels:Record<string,string>={RESOLVING:"Resolving source",EXTRACTING:"Reading the source",TRANSCRIBING:"Processing media",EXTRACTING_CLAIMS:"Finding checkable claims",SEARCHING_OFFICIAL:"Searching official sources",SEARCHING_FACT_CHECKS:"Reviewing prior fact-checks",SEARCHING_WEB:"Searching the public web",EVALUATING:"Assessing the evidence",COMPLETE:"Analysis complete",PARTIAL:"Analysis complete with limitations",FAILED:"Analysis failed"};
const glyphs:Record<string,string>={TEXT:"¶",IMAGE:"▧",AUDIO:"♪",VIDEO:"▶",LINKED_PAGE:"↗"};

function Coverage({artifacts}:{artifacts:ContentArtifact[]}){return <ul className="coverage-list">{artifacts.map((item,index)=><li className="coverage-item" key={`${item.kind}-${index}`}><span className="coverage-glyph">{glyphs[item.kind]}</span><span><strong>{item.kind.replace("_"," ")}</strong><small>{item.extractionMethod}</small></span><span className={`coverage-state ${item.coverage}`}>{item.coverage}</span></li>)}</ul>}

export function AnalysisView({analysisId,initialRecord}:{analysisId:string;initialRecord?:AnalysisRecord}){
  const [record,setRecord]=useState<AnalysisRecord|undefined>(initialRecord); const [loadError,setLoadError]=useState(""); const [roomCopied,setRoomCopied]=useState(false);
  useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;let delay=2000;async function poll(){try{const response=await fetch(`/api/analyses/${analysisId}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Analysis not found.");if(!active)return;setRecord(data);if(!["COMPLETE","PARTIAL","FAILED"].includes(data.stage)){delay=Math.min(10000,delay+1000);timer=setTimeout(poll,delay);}}catch(error){if(active)setLoadError(error instanceof Error?error.message:"Could not load analysis.");}}poll();return()=>{active=false;clearTimeout(timer)}},[analysisId]);
  if(loadError)return <div className="app-shell"><AppHeader/><main className="shell"><div className="failure">{loadError}</div></main></div>;
  if(!record)return <div className="app-shell"><AppHeader label="Opening analysis"/><main className="shell"><div className="analysis-layout"><section className="panel panel-pad"><div className="empty-state"><strong>Opening the evidence trail…</strong>Please wait while CivicLens locates this analysis.</div></section></div></main></div>;
  const result=record.result; const isDone=["COMPLETE","PARTIAL","FAILED"].includes(record.stage);
  const languages=result?.detectedLanguages.filter((language)=>language!=="und")||[];
  const roomPath=`/room/${roomIdForSource(record.source)}?analysis=${record.id}`;
  const copyRoom=async()=>{const url=`${window.location.origin}${roomPath}`;try{await navigator.clipboard.writeText(url);setRoomCopied(true);setTimeout(()=>setRoomCopied(false),2000)}catch{window.prompt("Copy this civic room link:",url)}};
  return <div className="app-shell"><AppHeader label={isDone?"Evidence trail":"Analysis in progress"}/><main className="shell analysis-layout"><section><div className="panel panel-pad"><span className="eyebrow">{record.source.kind.replace("_"," ")}</span><h1 className="analysis-title">{result?.title||"Reading the source"}</h1><a className="source-url" href={record.source.canonicalUrl} target="_blank" rel="noreferrer">{record.source.canonicalUrl}</a><div className="analysis-room-actions"><a className="secondary-button" href={roomPath}>↗ Open civic room</a><button className="secondary-button" onClick={copyRoom}>{roomCopied?"✓ Room link copied":"↗ Share civic room"}</button></div><div className="progress-card"><div className="progress-top"><strong>{stageLabels[record.stage]||record.stage}</strong><span>{record.progress}%</span></div><div className="progress-track"><div className="progress-bar" style={{width:`${record.progress}%`}}/></div></div>{result?.fixture&&<div className="fixture-banner"><strong>Development fixture.</strong> This result demonstrates the workflow and is not a factual determination. Add provider keys and set <code>FIXTURE_MODE=false</code> for live retrieval.</div>}{record.failureReason&&<div className="failure">{record.failureReason}</div>}</div>{result?.claims?.length?<div className="fact-stack">{result.claims.map((claim)=><FactCard claim={claim} key={claim.id}/>)}</div>:isDone&&record.stage!=="FAILED"?<div className="panel empty-state" style={{marginTop:16}}><strong>No checkable claims found</strong>CivicLens did not find a statement that met the checkability threshold.</div>:null}</section><aside className="side-stack"><section className="panel panel-pad"><h2 className="side-title">Content coverage</h2>{result?<Coverage artifacts={result.artifacts}/>:<p className="source-url">Coverage appears after extraction.</p>}{result?.artifacts.some((item)=>item.coverage!=="COMPLETE")&&<div className="coverage-banner">Partial means a layer still needs media access, transcription, or a manual upload. It is never treated as fully analyzed.</div>}</section><section className="panel panel-pad"><h2 className="side-title">Detected languages</h2><div className="language-cloud">{(languages.length?languages:["Detecting automatically…"]).map((language)=><span key={language}>{language}</span>)}</div></section><section className="panel panel-pad"><h2 className="side-title">Limits & fallback</h2>{result?.limitations.length?<ul className="limitation-list">{result.limitations.map((item)=><li key={item}>{item}</li>)}</ul>:<p className="source-url">No source-level limitations reported yet.</p>}<div style={{marginTop:18}}><ManualFallback/></div></section></aside></main></div>;
}
